---
save : 'product.save'
outStock : 'product.out_of_stock'
commissionLabel : 'profile.commission_label'
more : 'product.more'
option : 'product.option'
offers : 'product.offers'
viewDetails : 'cart.view_details'
request : 'product.request'
requested : 'product.requested'
addCart : 'cart.add_to_cart'
buyNow : 'cart.buy_now'
buyNowWithEMI: 'cart.buy_now_with_emi'
viewPlans: 'product.view_plans'
coupon: 'product.coupon'
